[project]
name = "weather-info"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.0",
    "dotenv>=0.9.9",
    "mcp[cli]>=1.17.0",
    "fastmcp>=0.4",
    "python-dotenv>=1.0.1",
]
